import "dotenv/config";
import cors from "cors";
import express from "express";
import { assessmentAttemptsRouter } from "./routes/assessmentAttempts.js";
import { assessmentQuestionsRouter } from "./routes/assessmentQuestions.js";
import { assessmentsRouter } from "./routes/assessments.js";
import { attendanceRouter } from "./routes/attendance.js";
import { analyticsRouter } from "./routes/analytics.js";
import { careerCounsellorRouter } from "./routes/careerCounsellor.js";
import { certificatesRouter } from "./routes/certificates.js";
import { chatbotRouter } from "./routes/chatbot.js";
import { contentTranslationsRouter } from "./routes/contentTranslations.js";
import { coursesRouter } from "./routes/courses.js";
import { employerSearchRouter } from "./routes/employerSearch.js";
import { faceEmbeddingsRouter } from "./routes/faceEmbeddings.js";
import { institutionsRouter } from "./routes/institutions.js";
import { jobInterestsRouter } from "./routes/jobInterests.js";
import { jobMatchingRouter } from "./routes/jobMatching.js";
import { jobsRouter } from "./routes/jobs.js";
import { lessonContentRouter } from "./routes/lessonContent.js";
import { lessonProgressRouter } from "./routes/lessonProgress.js";
import { lessonVideoRouter } from "./routes/lessonVideo.js";
import { lessonsRouter } from "./routes/lessons.js";
import { modulesRouter } from "./routes/modules.js";
import { nominationsRouter } from "./routes/nominations.js";
import { profileRouter } from "./routes/profile.js";
import { programmeProgressRouter } from "./routes/programmeProgress.js";
import { programmesRouter } from "./routes/programmes.js";
import { skillsRouter } from "./routes/skills.js";
import { timetableRouter } from "./routes/timetable.js";
import { usersRouter } from "./routes/users.js";
import { visibilitySettingsRouter } from "./routes/visibilitySettings.js";

export const app = express();

app.use(cors());
app.use(express.json());

app.get("/health", (_req, res) => {
  res.json({ status: "ok" });
});

app.use("/api", profileRouter);
app.use("/api", institutionsRouter);
app.use("/api", usersRouter);
app.use("/api", programmesRouter);
app.use("/api", programmeProgressRouter);
app.use("/api", nominationsRouter);
app.use("/api", timetableRouter);
app.use("/api", coursesRouter);
app.use("/api", modulesRouter);
app.use("/api", lessonsRouter);
app.use("/api", lessonProgressRouter);
app.use("/api", lessonContentRouter);
app.use("/api", lessonVideoRouter);
app.use("/api", contentTranslationsRouter);
app.use("/api", assessmentsRouter);
app.use("/api", assessmentQuestionsRouter);
app.use("/api", assessmentAttemptsRouter);
app.use("/api", certificatesRouter);
app.use("/api", attendanceRouter);
app.use("/api", faceEmbeddingsRouter);
app.use("/api", jobsRouter);
app.use("/api", jobInterestsRouter);
app.use("/api", jobMatchingRouter);
app.use("/api", visibilitySettingsRouter);
app.use("/api", employerSearchRouter);
app.use("/api", chatbotRouter);
app.use("/api", analyticsRouter);
app.use("/api", skillsRouter);
app.use("/api", careerCounsellorRouter);
